
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: course-management
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: course-management
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nest-app:
    build: .
    container_name: nest-app-course-management
    ports:
      - "3000:3000"
    environment:
      # Kết nối MongoDB và MySQL
      MONGO_URI: mongodb://mongo:27017/course-management
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DB: course-management
      # JWT Secret và PORT
      JWT_SECRET: ducchien0612@jwt_secret
      PORT: 3000
    depends_on:
      - mongo
      - mysql

volumes:
  mongo_data:
  mysql_data:
